# Generated by Django 5.2.8 on 2025-12-01 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_conversationsession_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('consigne', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='exercices/')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='api.cours')),
            ],
        ),
    ]
