# Generated by Django 5.2.8 on 2025-12-04 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_exercice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplicationCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='explications/audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='explications/video/')),
                ('texte', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explications', to='api.cours')),
            ],
        ),
    ]
